apiVersion: v1
kind: Service
metadata:
  name: {{ include "smooai-next.fullname" . }}
  labels:
    {{- include "smooai-next.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 3000 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "smooai-next.selectorLabels" . | nindent 4 }}
